"""Write a program to generate Fibonacci series of numbers.
    Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
  Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
   a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
   b) Generate the series until the element in the series is less than Max number.
"""
from Basics import Input

print("Problem Statement:", __doc__)

int1 = Input.fetchValidate('int', 1)[0]

a = 0
b = 1
arr1 = []
print(a, end=' ')
for x in range(1, int1 + 1):
    c = a + b
    if c <= int1:
        arr1.append(c)
    print(c, end=' ')
    a = b
    b = c

print("\nSeries less than %d is/are " % int1)
print(arr1, end=' ')
